# Tranquilpeak
# Version : 0.3.1-BETA
# Author : Thibaud Leprêtre

baseurl = "https://bloges.kanteron.com/"
languageCode = "en-us"
defaultContentLanguage = "es-es"
title = "Blog de Kanteron Systems en Castellano"
theme = "hugo-tranquilpeak-theme"
disqusShortname = "jorgecortell"
googleAnalytics = "UA-51273041-6"
paginate = 7
canonifyurls = true

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Kanteron Systems"
  bio = "Nuestro blog en Castellano"
  job = "Medicina de Precisión en el Punto de Atención al Paciente"
  location = "Valencia y Madrid | Nueva York | Londres"
  # Your Gravatar email. Overwrite `author.picture` everywhere in the blog
  gravatarEmail = ""
  # Your profile picture
  # Overwritten by your gravatar image if `author.gravatarEmail` is filled
  picture = "https://web.kanteron.com/assets/images/klogo-1-128x128.png"
  # Your Twitter username without the @. E.g : thibaudlepretre
  twitter = "kanteron"
  # Your google plus profile id. E.g : +ThibaudLepretre or 114625208755123718311
  googlePlus = "102193154533258755916"

# Menu Configuration
[[menu.main]]
  weight = 0
  identifier = "home"
  name = "Inicio blog"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 0
  identifier = "web"
  name = "Inicio web"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-globe\"></i>"
  url = "https://web.kanteron.com/"
[[menu.main]]
  weight = 1
  identifier = "categories"
  name = "Categorías"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
  url = "/categories"
[[menu.main]]
  weight = 2
  identifier = "tags"
  name = "Etiquetas"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
  url = "/tags"
[[menu.main]]
  weight = 3
  identifier = "archives"
  name = "Archivo"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
  url = "/archives"

[[menu.links]]
  weight = 0
  identifier = "english"
  name = "English"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-flag-o\"></i>"
  url = "https://blog.kanteron.com"
[[menu.links]]
  weight = 1
  identifier = "linkedin"
  name = "LinkedIn"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-linkedin\"></i>"
  url = "https://www.linkedin.com/company/kanteron-systems"
[[menu.links]]
  weight = 1
  identifier = "twitter"
  name = "Twitter"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-twitter\"></i>"
  url = "https://twitter.com/kanteron"
[[menu.links]]
  weight = 3
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/KanteronSystems"
#[[menu.links]]
#  weight = 1
#  identifier = "stackoverflow"
#  name = "Stack Overflow"
#  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-stack-overflow\"></i>"
#  url = "https://stackoverflow.com/users/636472/kakawait"

[[menu.misc]]
  weight = 0
  identifier = "rss"
  name = "RSS"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
  url = "/index.xml"

[params]
  # Customize date format use to render blog post date, categories and other
  # You must use date format used by Go Time package https://golang.org/pkg/time/
  # Months (not work with short month like "jan", "feb", etc) are translated if translation exists on i18n folders
  # Default format is: January 2, 2006
  dateFormat = "2 January 2006"

  # Global keywords configuration. Following keywords will be add to every pages
  # keywords = ["development", "next-gen"]

  # Hide sidebar on all article page to let article take full width to improve reading, and enjoy wide images and cover images. (true: enable, false: disable)
  clearReading = true

  # Define categories will create hierarchy between parents: `categories = ["foo", "bar"]` will consider "bar" a sub-category of "foo".
  # If false it will flat categories.
  hierarchicalCategories = true

  description = "Blog de Kanteron Systems"

  # Customization
  # Define the behavior of the sidebar
  # 1: Display extra large sidebar on extra large screen, large sidebar on large screen,
  #    medium sidebar on medium screen and header bar on small screen and
  # extra large sidebar is swiped on extra large screen and large sidebar on all lower screen (default)
  # 2: Display large sidebar on large screen, medium sidebar on medium screen and
  #    header bar on small screen and large sidebar is swiped
  # 3: Display medium sidebar on large and medium screen and header bar on small screen and
  #    medium sidebar is swiped
  # 4: Display header bar on all screens, extra large sidebar is swiped on extra large screen and
  #    large sidebar is swiped on all lower screens
  # 5: Display header bar on all screens and large sidebar is swiped on large screen
  # 6: Display header bar on all screens and medium sidebar is swiped
  sidebarBehavior = 1

  # Your blog cover picture. I STRONGLY recommend you to use a CDN to speed up loading of pages.
  # There is many free CDN like Cloudinary or you can also use indirectly
  # by using services like Google Photos.
  # Current image is on AWS S3 and delivered by AWS CloudFront.
  # Otherwise put your image in folder `static/_images/` (development)  or in `source/assets/images/` if you can't or don't want to build the theme,
  # and use relative url : `your-image.png`
  coverImage = "cover.jpg"

  # Display an image gallery at the end of a post which have photos variables (false: disabled, true: enabled)
  imageGallery = true

  # Display thumbnail image of each post on index pages (false: disabled, true: enabled)
  thumbnailImage = true
  # Display thumbnail image at the right of title in index pages (`right`, `left` or `bottom`)
  # Set this value to `right` if you have old posts to keep the old style on them
  # and define `thumbnailImagePosition` on a post to overwrite this setting
  thumbnailImagePosition = "bottom"
  # Automatically select the cover image or the first photo from the gallery of a post if there is no thumbnail image as the thumbnail image
  # Set this value to `true` if you have old posts that use the cover image or the first photo as the thumbnail image
  # and set `autoThumbnailImage` to `false` on a post to overwrite this setting
  autoThumbnailImage = true

  # Your favicon path, default is "/favicon.png"
  favicon = "/favicon.png"

  # Header configuration
  # The link at the right of the header is customizable
  # You can add a link (as an icon) at the right of the header instead of the author's gravatar image or author's picture.
  # By default, author's gravatar or author's picture is displayed.
  # url: /search
  # icon: search
  # class: st-search-show-outputs

  # Custom CSS. Put here your custom CSS files. They are loaded after the theme CSS;
  # they have to be referred from static root. Example
  # customCSS = ["css/foo.css"]

  # Custom JS. Put here your custom JS files. They are loaded after the theme JS;
  # they have to be referred from static root. Example
  # customJS = ["js/foo.js"]

#  [params.header.rightLink]
#    class = ""
#    icon = ""
#    url = "https://web.cortell.net/sobre.html"

  # Customize like of author avatar in sidebar
  [params.sidebar.profile]
   url = "https://web.kanteron.com"

  # Customize copyright value "© 2016 <CUSTOMIZATION>. All Rights Reserved"
 [params.footer]
   copyright = "CC0 Copyleft - Comparte"
